using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMS.Areas.DashBoard.ViewModels;
using HMS.Areas.ViewModels;
using HMS.Entities;
using HMS.Models;
using HMS.Services;
using HMS.ViewModels;

namespace HMS.Areas.DashBoard.Controllers
{
    public class AccomodationPackagesController : Controller
    {
        private AccomodationPackagesService accomodationPackageService = new AccomodationPackagesService();
        private AccomodationTypesService accomodationTypesService = new AccomodationTypesService();

        // GET: DashBoard/AccomodationType
        public ActionResult Index(string searchTerm, int? accomodationTypeID , int? page)
         {
            AccomodationPackagesListingViewModel model = new AccomodationPackagesListingViewModel();

            //var dummyItems = Enumerable.Range(1, 150).Select(x => "Item " + x);
            
			 

            //model.AccomodationPackages = accomodationPackageService.GetAllAccomodationPackages();
            model.AccomodationPackages = accomodationPackageService.SearchAccomodationPackages(searchTerm , accomodationTypeID);
            model.totalRecord = model.AccomodationPackages.Count();

            //pagination logic start from here
            var pager = new Pager(model.totalRecord, page);

            model.AccomodationPackages =
                model.AccomodationPackages.Skip((pager.CurrentPage - 1)*pager.PageSize).Take(pager.PageSize).ToList();

            model.SearchTerm = searchTerm;
            model.AccomodationTypes = accomodationTypesService.GetAllAccomodationTypes();
            model.AccomodationTypeID = accomodationTypeID;
            model.pager = pager;
           
            

            return View(model);
        }

        public ActionResult Listing()
        {
            AccomodationPackagesListingViewModel model = new AccomodationPackagesListingViewModel();
            model.AccomodationPackages = accomodationPackageService.GetAllAccomodationPackages();
            return PartialView("_Listing", model);
        }

        [HttpGet]
        public ActionResult Action(int? ID, bool isDelete = false)
        {
            AccomodationPackagesActionViewModel model = new AccomodationPackagesActionViewModel();
            ViewBag.isDelete = isDelete;


            if (ID.HasValue && isDelete)
            {
                //delete here
                AccomodationPackage accomodationPackage = accomodationPackageService.GetAccomodationPackageById(ID);
                model.Id = accomodationPackage.Id;
                model.Name = accomodationPackage.Name;
                model.NoOfRoom = accomodationPackage.NoOfRoom;
                model.FeePerNight = accomodationPackage.FeePerNight;
                model.AccomodationType = accomodationPackage.AccomodationType;
                model.AccomodationPackagePictures = accomodationPackage.AccomodationPackagePictures;
            }

            else if (ID.HasValue && isDelete == false)
            {
                //edit here
               AccomodationPackage accomodationPackage = accomodationPackageService.GetAccomodationPackageById(ID);
                model.Id = accomodationPackage.Id;
                model.AccomodationTypeId = accomodationPackage.AccomodationTypeId;
                model.Name = accomodationPackage.Name;
                model.NoOfRoom = accomodationPackage.NoOfRoom;
                model.FeePerNight = accomodationPackage.FeePerNight;
                model.AccomodationPackagePictures = accomodationPackage.AccomodationPackagePictures;
            }
            else
            {
                //new entry
                
            }
            model.AccomodationTypes = accomodationTypesService.GetAllAccomodationTypes();
            return PartialView("_Action", model);
        }

        [HttpPost]

        public JsonResult Action(AccomodationPackagesActionViewModel model, bool isDeleted = false)
        {
            

            JsonResult json = new JsonResult();
            var result = false;

            if (model.Id > 0 && isDeleted == false)
            {
                //edit here
                // first break array of integers passed by view 

                List<int> pictureIds = string.IsNullOrEmpty(model.PicIDs) ?  new List<int>() : model.PicIDs.Split(',').Select(a => int.Parse(a)).ToList();
                //using linq generated by vs
                List<AccomodationPackagePicture> list = pictureIds.Select(id => new AccomodationPackagePicture() {AccomodationPackageId = model.Id ,PictureId = id }).ToList();

                AccomodationPackage accomodationPackage = new AccomodationPackage()
                {Id = model.Id, Name = model.Name, NoOfRoom = model.NoOfRoom ,
                    FeePerNight = model.FeePerNight
                    , AccomodationTypeId = model.AccomodationTypeId , AccomodationPackagePictures = list};

                result = accomodationPackageService.UpdateAccomodationPackages(accomodationPackage);
            }
            else if (model.Id > 0 && isDeleted == true)
            {
                //delete here
                result = accomodationPackageService.DeleteAccomodationPackages(model.Id);
            }

            else
            {
                //first create object then add
                AccomodationPackage accomodationPackage = new AccomodationPackage();
                // first break array of integers passed by view 

                List<int> pictureIds = string.IsNullOrEmpty(model.PicIDs) ?  new List<int>() : model.PicIDs.Split(',').Select(a => int.Parse(a)).ToList();

                accomodationPackage.AccomodationTypeId = model.AccomodationTypeId;
                accomodationPackage.Name = model.Name;
                accomodationPackage.NoOfRoom = model.NoOfRoom;
                accomodationPackage.FeePerNight = model.FeePerNight;
                //accomodationPackage.AccomodationPackagePictures = model.AccomodationPackagePictures;

                ////my method easy one
                //List<AccomodationPackagePicture> list =  new AccomodationPackagePicture()
                //foreach (var id in pictureIds)
                //{
                //    var accomodationPics = new AccomodationPackagePicture() {AccomodationPackageId = accomodationPackage.Id , PictureId = id};
                //    list.Add(accomodationPics);
                //} 
                
                
                //using linq generated by vs
                List<AccomodationPackagePicture> list = pictureIds.Select(id => new AccomodationPackagePicture() {PictureId = id}).ToList();


                accomodationPackage.AccomodationPackagePictures = list;

                result = accomodationPackageService.SaveAccomodationPackages(accomodationPackage);

            }

            if (result)
            {
                json.Data = new { success = true };
            }
            else
            {
                json.Data = new { success = false, Messag = "Unable to Perform Operation in Accomodation Type." };
            }

            return json;


        }

        public ActionResult UploadPictures()
        {


            //var form = Request.Form;
           
            if (Request.Files.Count > 0)  

    {
        try
        {
            //  Get all files from Request object  
            var files = Request.Files;

            for (int i = 0; i < files.Count; i++)
            {
                var pictures = files[i];
                string fileName;

                // Checking for Internet Explorer  
                if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                {
                    string[] testfiles = pictures.FileName.Split(new char[] {'\\'});
                    fileName = testfiles[testfiles.Length - 1];
                }
                else
                {
                    fileName = Guid.NewGuid() + Path.GetExtension(pictures.FileName);
                }

                // Get the complete folder path and store the file inside it.  
                fileName = Path.Combine(Server.MapPath("~/images/site"), fileName);
                pictures.SaveAs(fileName);
            }
            // Returns message that successfully uploaded  
        }
        catch (Exception ex)
        {
            return Json("Error occurred. Error details: " + ex.Message);
        }
    }  

        return View();
        }



    }
}